//------------------------------------------------------------------------------
// <auto-generated>
//     Deze code is gegenereerd met een hulpprogramma.
//     Runtime-versie:4.0.30319.18046
//
//     Als u wijzigingen aanbrengt in dit bestand, kan dit onjuist gedrag veroorzaken wanneer
//     de code wordt gegenereerd.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortableLibQNH.ijmobile.bjzlimburg.nl {
    
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="PortableLibQNH.ijmobile.bjzlimburg.nl", ConfigurationName="IJMobileSoap")]
public interface IJMobileSoap {
    
    // CODEGEN: Er wordt een berichtcontract gegenereerd omdat de wrapper-naamruimte (http://tempuri.org/) van bericht LoginRequest niet overeenkomt met de standaardwaarde (PortableLibQNH.ijmobile.bjzlimburg.nl)
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJMobileSoap/LoginRequest", ReplyAction="http://tempuri.org/IJMobileSoap/LoginResponse")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    LoginResponse Login(LoginRequest request);
    
    // CODEGEN: Er wordt een berichtcontract gegenereerd omdat de wrapper-naamruimte (http://tempuri.org/) van bericht GeefCaseLoadRequest niet overeenkomt met de standaardwaarde (PortableLibQNH.ijmobile.bjzlimburg.nl)
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJMobileSoap/GeefCaseLoadRequest", ReplyAction="http://tempuri.org/IJMobileSoap/GeefCaseLoadResponse")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    GeefCaseLoadResponse GeefCaseLoad(GeefCaseLoadRequest request);
    
    // CODEGEN: Er wordt een berichtcontract gegenereerd omdat de wrapper-naamruimte (http://tempuri.org/) van bericht VoegContactJournaalToeRequest niet overeenkomt met de standaardwaarde (PortableLibQNH.ijmobile.bjzlimburg.nl)
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJMobileSoap/VoegContactJournaalToeRequest", ReplyAction="http://tempuri.org/IJMobileSoap/VoegContactJournaalToeResponse")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    VoegContactJournaalToeResponse VoegContactJournaalToe(VoegContactJournaalToeRequest request);
    
    // CODEGEN: Er wordt een berichtcontract gegenereerd omdat de wrapper-naamruimte (http://tempuri.org/) van bericht VoegContactJournalenToeRequest niet overeenkomt met de standaardwaarde (PortableLibQNH.ijmobile.bjzlimburg.nl)
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJMobileSoap/VoegContactJournalenToeRequest", ReplyAction="http://tempuri.org/IJMobileSoap/VoegContactJournalenToeResponse")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    VoegContactJournalenToeResponse VoegContactJournalenToe(VoegContactJournalenToeRequest request);
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="Login", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
public partial class LoginRequest {
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
    public string loginNaam;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
    public string wachtwoord;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
    public string deviceID;
    
    public LoginRequest() {
    }
    
    public LoginRequest(string loginNaam, string wachtwoord, string deviceID) {
        this.loginNaam = loginNaam;
        this.wachtwoord = wachtwoord;
        this.deviceID = deviceID;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="LoginResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
public partial class LoginResponse {
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
    public LoginResultaat LoginResult;
    
    public LoginResponse() {
    }
    
    public LoginResponse(LoginResultaat LoginResult) {
        this.LoginResult = LoginResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="GeefCaseLoad", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
public partial class GeefCaseLoadRequest {
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
    public string loginToken;
    
    public GeefCaseLoadRequest() {
    }
    
    public GeefCaseLoadRequest(string loginToken) {
        this.loginToken = loginToken;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="GeefCaseLoadResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
public partial class GeefCaseLoadResponse {
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
    public CaseloadResult GeefCaseLoadResult;
    
    public GeefCaseLoadResponse() {
    }
    
    public GeefCaseLoadResponse(CaseloadResult GeefCaseLoadResult) {
        this.GeefCaseLoadResult = GeefCaseLoadResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="VoegContactJournaalToe", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
public partial class VoegContactJournaalToeRequest {
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
    public string loginToken;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
    public string onderwerp;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
    public string inhoud;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
    public int hulpverleningID;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
    public System.DateTime datum;
    
    public VoegContactJournaalToeRequest() {
    }
    
    public VoegContactJournaalToeRequest(string loginToken, string onderwerp, string inhoud, int hulpverleningID, System.DateTime datum) {
        this.loginToken = loginToken;
        this.onderwerp = onderwerp;
        this.inhoud = inhoud;
        this.hulpverleningID = hulpverleningID;
        this.datum = datum;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="VoegContactJournaalToeResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
public partial class VoegContactJournaalToeResponse {
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
    public SessionStatus VoegContactJournaalToeResult;
    
    public VoegContactJournaalToeResponse() {
    }
    
    public VoegContactJournaalToeResponse(SessionStatus VoegContactJournaalToeResult) {
        this.VoegContactJournaalToeResult = VoegContactJournaalToeResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="VoegContactJournalenToe", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
public partial class VoegContactJournalenToeRequest {
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
    public string loginToken;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
    public ContactJournaal[] journalen;
    
    public VoegContactJournalenToeRequest() {
    }
    
    public VoegContactJournalenToeRequest(string loginToken, ContactJournaal[] journalen) {
        this.loginToken = loginToken;
        this.journalen = journalen;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="VoegContactJournalenToeResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
public partial class VoegContactJournalenToeResponse {
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
    public SessionStatus VoegContactJournalenToeResult;
    
    public VoegContactJournalenToeResponse() {
    }
    
    public VoegContactJournalenToeResponse(SessionStatus VoegContactJournalenToeResult) {
        this.VoegContactJournalenToeResult = VoegContactJournalenToeResult;
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IJMobileSoapChannel : IJMobileSoap, System.ServiceModel.IClientChannel {
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class JMobileSoapClient : System.ServiceModel.ClientBase<IJMobileSoap>, IJMobileSoap {
    
    public JMobileSoapClient() {
    }
    
    public JMobileSoapClient(string endpointConfigurationName) : 
            base(endpointConfigurationName) {
    }
    
    public JMobileSoapClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress) {
    }
    
    public JMobileSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress) {
    }
    
    public JMobileSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress) {
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    LoginResponse IJMobileSoap.Login(LoginRequest request) {
        return base.Channel.Login(request);
    }
    
    public LoginResultaat Login(string loginNaam, string wachtwoord, string deviceID) {
        LoginRequest inValue = new LoginRequest();
        inValue.loginNaam = loginNaam;
        inValue.wachtwoord = wachtwoord;
        inValue.deviceID = deviceID;
        LoginResponse retVal = ((IJMobileSoap)(this)).Login(inValue);
        return retVal.LoginResult;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    GeefCaseLoadResponse IJMobileSoap.GeefCaseLoad(GeefCaseLoadRequest request) {
        return base.Channel.GeefCaseLoad(request);
    }
    
    public CaseloadResult GeefCaseLoad(string loginToken) {
        GeefCaseLoadRequest inValue = new GeefCaseLoadRequest();
        inValue.loginToken = loginToken;
        GeefCaseLoadResponse retVal = ((IJMobileSoap)(this)).GeefCaseLoad(inValue);
        return retVal.GeefCaseLoadResult;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    VoegContactJournaalToeResponse IJMobileSoap.VoegContactJournaalToe(VoegContactJournaalToeRequest request) {
        return base.Channel.VoegContactJournaalToe(request);
    }
    
    public SessionStatus VoegContactJournaalToe(string loginToken, string onderwerp, string inhoud, int hulpverleningID, System.DateTime datum) {
        VoegContactJournaalToeRequest inValue = new VoegContactJournaalToeRequest();
        inValue.loginToken = loginToken;
        inValue.onderwerp = onderwerp;
        inValue.inhoud = inhoud;
        inValue.hulpverleningID = hulpverleningID;
        inValue.datum = datum;
        VoegContactJournaalToeResponse retVal = ((IJMobileSoap)(this)).VoegContactJournaalToe(inValue);
        return retVal.VoegContactJournaalToeResult;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    VoegContactJournalenToeResponse IJMobileSoap.VoegContactJournalenToe(VoegContactJournalenToeRequest request) {
        return base.Channel.VoegContactJournalenToe(request);
    }
    
    public SessionStatus VoegContactJournalenToe(string loginToken, ContactJournaal[] journalen) {
        VoegContactJournalenToeRequest inValue = new VoegContactJournalenToeRequest();
        inValue.loginToken = loginToken;
        inValue.journalen = journalen;
        VoegContactJournalenToeResponse retVal = ((IJMobileSoap)(this)).VoegContactJournalenToe(inValue);
        return retVal.VoegContactJournalenToeResult;
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="PortableLibQNH.ijmobile.bjzlimburg.nl", ConfigurationName="IJMobileHttpGet")]
public interface IJMobileHttpGet {
    
    // CODEGEN: Er wordt een berichtcontract gegenereerd omdat de bewerking Login niet RPC of in een document genest is.
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJMobileHttpGet/LoginRequest", ReplyAction="http://tempuri.org/IJMobileHttpGet/LoginResponse")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    LoginResponse1 Login(LoginRequest1 request);
    
    // CODEGEN: Er wordt een berichtcontract gegenereerd omdat de bewerking GeefCaseLoad niet RPC of in een document genest is.
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJMobileHttpGet/GeefCaseLoadRequest", ReplyAction="http://tempuri.org/IJMobileHttpGet/GeefCaseLoadResponse")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    GeefCaseLoadResponse1 GeefCaseLoad(GeefCaseLoadRequest1 request);
    
    // CODEGEN: Er wordt een berichtcontract gegenereerd omdat de bewerking VoegContactJournaalToe niet RPC of in een document genest is.
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJMobileHttpGet/VoegContactJournaalToeRequest", ReplyAction="http://tempuri.org/IJMobileHttpGet/VoegContactJournaalToeResponse")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    VoegContactJournaalToeResponse1 VoegContactJournaalToe(VoegContactJournaalToeRequest1 request);
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class LoginRequest1 {
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
    public string loginNaam;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
    public string wachtwoord;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
    public string deviceID;
    
    public LoginRequest1() {
    }
    
    public LoginRequest1(string loginNaam, string wachtwoord, string deviceID) {
        this.loginNaam = loginNaam;
        this.wachtwoord = wachtwoord;
        this.deviceID = deviceID;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class LoginResponse1 {
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public LoginResultaat LoginResultaat;
    
    public LoginResponse1() {
    }
    
    public LoginResponse1(LoginResultaat LoginResultaat) {
        this.LoginResultaat = LoginResultaat;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class GeefCaseLoadRequest1 {
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
    public string loginToken;
    
    public GeefCaseLoadRequest1() {
    }
    
    public GeefCaseLoadRequest1(string loginToken) {
        this.loginToken = loginToken;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class GeefCaseLoadResponse1 {
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public CaseloadResult CaseloadResult;
    
    public GeefCaseLoadResponse1() {
    }
    
    public GeefCaseLoadResponse1(CaseloadResult CaseloadResult) {
        this.CaseloadResult = CaseloadResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class VoegContactJournaalToeRequest1 {
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
    public string loginToken;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
    public string onderwerp;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
    public string inhoud;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
    public string hulpverleningID;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
    public string datum;
    
    public VoegContactJournaalToeRequest1() {
    }
    
    public VoegContactJournaalToeRequest1(string loginToken, string onderwerp, string inhoud, string hulpverleningID, string datum) {
        this.loginToken = loginToken;
        this.onderwerp = onderwerp;
        this.inhoud = inhoud;
        this.hulpverleningID = hulpverleningID;
        this.datum = datum;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class VoegContactJournaalToeResponse1 {
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
    public SessionStatus SessionStatus;
    
    public VoegContactJournaalToeResponse1() {
    }
    
    public VoegContactJournaalToeResponse1(SessionStatus SessionStatus) {
        this.SessionStatus = SessionStatus;
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IJMobileHttpGetChannel : IJMobileHttpGet, System.ServiceModel.IClientChannel {
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class JMobileHttpGetClient : System.ServiceModel.ClientBase<IJMobileHttpGet>, IJMobileHttpGet {
    
    public JMobileHttpGetClient() {
    }
    
    public JMobileHttpGetClient(string endpointConfigurationName) : 
            base(endpointConfigurationName) {
    }
    
    public JMobileHttpGetClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress) {
    }
    
    public JMobileHttpGetClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress) {
    }
    
    public JMobileHttpGetClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress) {
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    LoginResponse1 IJMobileHttpGet.Login(LoginRequest1 request) {
        return base.Channel.Login(request);
    }
    
    public LoginResultaat Login(string loginNaam, string wachtwoord, string deviceID) {
        LoginRequest1 inValue = new LoginRequest1();
        inValue.loginNaam = loginNaam;
        inValue.wachtwoord = wachtwoord;
        inValue.deviceID = deviceID;
        LoginResponse1 retVal = ((IJMobileHttpGet)(this)).Login(inValue);
        return retVal.LoginResultaat;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    GeefCaseLoadResponse1 IJMobileHttpGet.GeefCaseLoad(GeefCaseLoadRequest1 request) {
        return base.Channel.GeefCaseLoad(request);
    }
    
    public CaseloadResult GeefCaseLoad(string loginToken) {
        GeefCaseLoadRequest1 inValue = new GeefCaseLoadRequest1();
        inValue.loginToken = loginToken;
        GeefCaseLoadResponse1 retVal = ((IJMobileHttpGet)(this)).GeefCaseLoad(inValue);
        return retVal.CaseloadResult;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    VoegContactJournaalToeResponse1 IJMobileHttpGet.VoegContactJournaalToe(VoegContactJournaalToeRequest1 request) {
        return base.Channel.VoegContactJournaalToe(request);
    }
    
    public SessionStatus VoegContactJournaalToe(string loginToken, string onderwerp, string inhoud, string hulpverleningID, string datum) {
        VoegContactJournaalToeRequest1 inValue = new VoegContactJournaalToeRequest1();
        inValue.loginToken = loginToken;
        inValue.onderwerp = onderwerp;
        inValue.inhoud = inhoud;
        inValue.hulpverleningID = hulpverleningID;
        inValue.datum = datum;
        VoegContactJournaalToeResponse1 retVal = ((IJMobileHttpGet)(this)).VoegContactJournaalToe(inValue);
        return retVal.SessionStatus;
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="PortableLibQNH.ijmobile.bjzlimburg.nl", ConfigurationName="IJMobileHttpPost")]
public interface IJMobileHttpPost {
    
    // CODEGEN: Er wordt een berichtcontract gegenereerd omdat de bewerking Login niet RPC of in een document genest is.
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJMobileHttpPost/LoginRequest", ReplyAction="http://tempuri.org/IJMobileHttpPost/LoginResponse")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    LoginResponse2 Login(LoginRequest2 request);
    
    // CODEGEN: Er wordt een berichtcontract gegenereerd omdat de bewerking GeefCaseLoad niet RPC of in een document genest is.
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJMobileHttpPost/GeefCaseLoadRequest", ReplyAction="http://tempuri.org/IJMobileHttpPost/GeefCaseLoadResponse")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    GeefCaseLoadResponse2 GeefCaseLoad(GeefCaseLoadRequest2 request);
    
    // CODEGEN: Er wordt een berichtcontract gegenereerd omdat de bewerking VoegContactJournaalToe niet RPC of in een document genest is.
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJMobileHttpPost/VoegContactJournaalToeRequest", ReplyAction="http://tempuri.org/IJMobileHttpPost/VoegContactJournaalToeResponse")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    VoegContactJournaalToeResponse2 VoegContactJournaalToe(VoegContactJournaalToeRequest2 request);
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class LoginRequest2 {
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
    public string loginNaam;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
    public string wachtwoord;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
    public string deviceID;
    
    public LoginRequest2() {
    }
    
    public LoginRequest2(string loginNaam, string wachtwoord, string deviceID) {
        this.loginNaam = loginNaam;
        this.wachtwoord = wachtwoord;
        this.deviceID = deviceID;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class LoginResponse2 {
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public LoginResultaat LoginResultaat;
    
    public LoginResponse2() {
    }
    
    public LoginResponse2(LoginResultaat LoginResultaat) {
        this.LoginResultaat = LoginResultaat;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class GeefCaseLoadRequest2 {
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
    public string loginToken;
    
    public GeefCaseLoadRequest2() {
    }
    
    public GeefCaseLoadRequest2(string loginToken) {
        this.loginToken = loginToken;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class GeefCaseLoadResponse2 {
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public CaseloadResult CaseloadResult;
    
    public GeefCaseLoadResponse2() {
    }
    
    public GeefCaseLoadResponse2(CaseloadResult CaseloadResult) {
        this.CaseloadResult = CaseloadResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class VoegContactJournaalToeRequest2 {
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
    public string loginToken;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
    public string onderwerp;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
    public string inhoud;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
    public string hulpverleningID;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
    public string datum;
    
    public VoegContactJournaalToeRequest2() {
    }
    
    public VoegContactJournaalToeRequest2(string loginToken, string onderwerp, string inhoud, string hulpverleningID, string datum) {
        this.loginToken = loginToken;
        this.onderwerp = onderwerp;
        this.inhoud = inhoud;
        this.hulpverleningID = hulpverleningID;
        this.datum = datum;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class VoegContactJournaalToeResponse2 {
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
    public SessionStatus SessionStatus;
    
    public VoegContactJournaalToeResponse2() {
    }
    
    public VoegContactJournaalToeResponse2(SessionStatus SessionStatus) {
        this.SessionStatus = SessionStatus;
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IJMobileHttpPostChannel : IJMobileHttpPost, System.ServiceModel.IClientChannel {
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class JMobileHttpPostClient : System.ServiceModel.ClientBase<IJMobileHttpPost>, IJMobileHttpPost {
    
    public JMobileHttpPostClient() {
    }
    
    public JMobileHttpPostClient(string endpointConfigurationName) : 
            base(endpointConfigurationName) {
    }
    
    public JMobileHttpPostClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress) {
    }
    
    public JMobileHttpPostClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress) {
    }
    
    public JMobileHttpPostClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress) {
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    LoginResponse2 IJMobileHttpPost.Login(LoginRequest2 request) {
        return base.Channel.Login(request);
    }
    
    public LoginResultaat Login(string loginNaam, string wachtwoord, string deviceID) {
        LoginRequest2 inValue = new LoginRequest2();
        inValue.loginNaam = loginNaam;
        inValue.wachtwoord = wachtwoord;
        inValue.deviceID = deviceID;
        LoginResponse2 retVal = ((IJMobileHttpPost)(this)).Login(inValue);
        return retVal.LoginResultaat;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    GeefCaseLoadResponse2 IJMobileHttpPost.GeefCaseLoad(GeefCaseLoadRequest2 request) {
        return base.Channel.GeefCaseLoad(request);
    }
    
    public CaseloadResult GeefCaseLoad(string loginToken) {
        GeefCaseLoadRequest2 inValue = new GeefCaseLoadRequest2();
        inValue.loginToken = loginToken;
        GeefCaseLoadResponse2 retVal = ((IJMobileHttpPost)(this)).GeefCaseLoad(inValue);
        return retVal.CaseloadResult;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    VoegContactJournaalToeResponse2 IJMobileHttpPost.VoegContactJournaalToe(VoegContactJournaalToeRequest2 request) {
        return base.Channel.VoegContactJournaalToe(request);
    }
    
    public SessionStatus VoegContactJournaalToe(string loginToken, string onderwerp, string inhoud, string hulpverleningID, string datum) {
        VoegContactJournaalToeRequest2 inValue = new VoegContactJournaalToeRequest2();
        inValue.loginToken = loginToken;
        inValue.onderwerp = onderwerp;
        inValue.inhoud = inhoud;
        inValue.hulpverleningID = hulpverleningID;
        inValue.datum = datum;
        VoegContactJournaalToeResponse2 retVal = ((IJMobileHttpPost)(this)).VoegContactJournaalToe(inValue);
        return retVal.SessionStatus;
    }
}


/// <opmerkingen/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
public partial class LoginResultaat {
    
    private string naamMedewerkerField;
    
    private LoginStatus statusField;
    
    private string tokenField;
    
    /// <opmerkingen/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public string NaamMedewerker {
        get {
            return this.naamMedewerkerField;
        }
        set {
            this.naamMedewerkerField = value;
        }
    }
    
    /// <opmerkingen/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public LoginStatus Status {
        get {
            return this.statusField;
        }
        set {
            this.statusField = value;
        }
    }
    
    /// <opmerkingen/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public string Token {
        get {
            return this.tokenField;
        }
        set {
            this.tokenField = value;
        }
    }
}

/// <opmerkingen/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
public enum LoginStatus {
    
    /// <opmerkingen/>
    Succes,
    
    /// <opmerkingen/>
    ToestelGeblokkeerd,
    
    /// <opmerkingen/>
    OngeldigeGegevens,
    
    /// <opmerkingen/>
    GebruikerGeblokkeerd,
    
    /// <opmerkingen/>
    GeneriekeFout,
}

/// <opmerkingen/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
public partial class ContactJournaal {
    
    private int hulpVerleningIdField;
    
    private string onderwerpField;
    
    private string inhoudField;
    
    private System.DateTime datumField;
    
    private int medewerkerIDField;
    
    /// <opmerkingen/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public int HulpVerleningId {
        get {
            return this.hulpVerleningIdField;
        }
        set {
            this.hulpVerleningIdField = value;
        }
    }
    
    /// <opmerkingen/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public string Onderwerp {
        get {
            return this.onderwerpField;
        }
        set {
            this.onderwerpField = value;
        }
    }
    
    /// <opmerkingen/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public string Inhoud {
        get {
            return this.inhoudField;
        }
        set {
            this.inhoudField = value;
        }
    }
    
    /// <opmerkingen/>
    [System.Xml.Serialization.XmlElementAttribute(Order=3)]
    public System.DateTime Datum {
        get {
            return this.datumField;
        }
        set {
            this.datumField = value;
        }
    }
    
    /// <opmerkingen/>
    [System.Xml.Serialization.XmlElementAttribute(Order=4)]
    public int MedewerkerID {
        get {
            return this.medewerkerIDField;
        }
        set {
            this.medewerkerIDField = value;
        }
    }
}

/// <opmerkingen/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.qnh.nl/xsd/caseload")]
public partial class BereikbaarheidType {
    
    private BereikbaarheidTypeBereikbaar[] bereikbaarField;
    
    private string[] textField;
    
    /// <opmerkingen/>
    [System.Xml.Serialization.XmlElementAttribute("Bereikbaar", Order=0)]
    public BereikbaarheidTypeBereikbaar[] Bereikbaar {
        get {
            return this.bereikbaarField;
        }
        set {
            this.bereikbaarField = value;
        }
    }
    
    /// <opmerkingen/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string[] Text {
        get {
            return this.textField;
        }
        set {
            this.textField = value;
        }
    }
}

/// <opmerkingen/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.qnh.nl/xsd/caseload")]
public partial class BereikbaarheidTypeBereikbaar {
    
    private string soortField;
    
    private string waardeField;
    
    private string opmerkingenField;
    
    /// <opmerkingen/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public string Soort {
        get {
            return this.soortField;
        }
        set {
            this.soortField = value;
        }
    }
    
    /// <opmerkingen/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public string Waarde {
        get {
            return this.waardeField;
        }
        set {
            this.waardeField = value;
        }
    }
    
    /// <opmerkingen/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public string Opmerkingen {
        get {
            return this.opmerkingenField;
        }
        set {
            this.opmerkingenField = value;
        }
    }
}

/// <opmerkingen/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.qnh.nl/xsd/caseload")]
public partial class AdresType {
    
    private AdresTypeAdres[] adresField;
    
    private string[] textField;
    
    /// <opmerkingen/>
    [System.Xml.Serialization.XmlElementAttribute("Adres", Order=0)]
    public AdresTypeAdres[] Adres {
        get {
            return this.adresField;
        }
        set {
            this.adresField = value;
        }
    }
    
    /// <opmerkingen/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string[] Text {
        get {
            return this.textField;
        }
        set {
            this.textField = value;
        }
    }
}

/// <opmerkingen/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.qnh.nl/xsd/caseload")]
public partial class AdresTypeAdres {
    
    private string straatField;
    
    private short huisNummerField;
    
    private string postcodeField;
    
    private string plaatsField;
    
    /// <opmerkingen/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public string Straat {
        get {
            return this.straatField;
        }
        set {
            this.straatField = value;
        }
    }
    
    /// <opmerkingen/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public short HuisNummer {
        get {
            return this.huisNummerField;
        }
        set {
            this.huisNummerField = value;
        }
    }
    
    /// <opmerkingen/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public string Postcode {
        get {
            return this.postcodeField;
        }
        set {
            this.postcodeField = value;
        }
    }
    
    /// <opmerkingen/>
    [System.Xml.Serialization.XmlElementAttribute(Order=3)]
    public string Plaats {
        get {
            return this.plaatsField;
        }
        set {
            this.plaatsField = value;
        }
    }
}

/// <opmerkingen/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
public partial class CaseloadResult {
    
    private SessionStatus statusField;
    
    private JeugdigenJeugdige[] jeugdigenField;
    
    /// <opmerkingen/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public SessionStatus Status {
        get {
            return this.statusField;
        }
        set {
            this.statusField = value;
        }
    }
    
    /// <opmerkingen/>
    [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
    [System.Xml.Serialization.XmlArrayItemAttribute("Jeugdige", Namespace="http://www.qnh.nl/xsd/caseload", IsNullable=false)]
    public JeugdigenJeugdige[] Jeugdigen {
        get {
            return this.jeugdigenField;
        }
        set {
            this.jeugdigenField = value;
        }
    }
}

/// <opmerkingen/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
public enum SessionStatus {
    
    /// <opmerkingen/>
    Ok,
    
    /// <opmerkingen/>
    Verlopen,
    
    /// <opmerkingen/>
    Ongeldig,
}

/// <opmerkingen/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.qnh.nl/xsd/caseload")]
public partial class JeugdigenJeugdige {
    
    private int idField;
    
    private int hulpverleningIdField;
    
    private string typeHulpverleningField;
    
    private string isEersteContactPersoonField;
    
    private string naamField;
    
    private GeslachtType geslachtField;
    
    private System.DateTime geboorteDatumField;
    
    private AdresType adressenField;
    
    private BereikbaarheidType bereikbaarheidField;
    
    private string aantekeningenField;
    
    private ArrayOfJeugdigenJeugdigeRelatieRelatie[] relatiesField;
    
    private JeugdigenJeugdigeContactJournaals contactJournaalsField;
    
    private JeugdigenJeugdigeSamenvatting samenvattingField;
    
    /// <opmerkingen/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public int Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <opmerkingen/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public int HulpverleningId {
        get {
            return this.hulpverleningIdField;
        }
        set {
            this.hulpverleningIdField = value;
        }
    }
    
    /// <opmerkingen/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public string TypeHulpverlening {
        get {
            return this.typeHulpverleningField;
        }
        set {
            this.typeHulpverleningField = value;
        }
    }
    
    /// <opmerkingen/>
    [System.Xml.Serialization.XmlElementAttribute(Order=3)]
    public string IsEersteContactPersoon {
        get {
            return this.isEersteContactPersoonField;
        }
        set {
            this.isEersteContactPersoonField = value;
        }
    }
    
    /// <opmerkingen/>
    [System.Xml.Serialization.XmlElementAttribute(Order=4)]
    public string Naam {
        get {
            return this.naamField;
        }
        set {
            this.naamField = value;
        }
    }
    
    /// <opmerkingen/>
    [System.Xml.Serialization.XmlElementAttribute(Order=5)]
    public GeslachtType Geslacht {
        get {
            return this.geslachtField;
        }
        set {
            this.geslachtField = value;
        }
    }
    
    /// <opmerkingen/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=6)]
    public System.DateTime GeboorteDatum {
        get {
            return this.geboorteDatumField;
        }
        set {
            this.geboorteDatumField = value;
        }
    }
    
    /// <opmerkingen/>
    [System.Xml.Serialization.XmlElementAttribute(Order=7)]
    public AdresType Adressen {
        get {
            return this.adressenField;
        }
        set {
            this.adressenField = value;
        }
    }
    
    /// <opmerkingen/>
    [System.Xml.Serialization.XmlElementAttribute(Order=8)]
    public BereikbaarheidType Bereikbaarheid {
        get {
            return this.bereikbaarheidField;
        }
        set {
            this.bereikbaarheidField = value;
        }
    }
    
    /// <opmerkingen/>
    [System.Xml.Serialization.XmlElementAttribute(Order=9)]
    public string Aantekeningen {
        get {
            return this.aantekeningenField;
        }
        set {
            this.aantekeningenField = value;
        }
    }
    
    /// <opmerkingen/>
    [System.Xml.Serialization.XmlArrayAttribute(Order=10)]
    [System.Xml.Serialization.XmlArrayItemAttribute("Relatie", IsNullable=false)]
    public ArrayOfJeugdigenJeugdigeRelatieRelatie[] Relaties {
        get {
            return this.relatiesField;
        }
        set {
            this.relatiesField = value;
        }
    }
    
    /// <opmerkingen/>
    [System.Xml.Serialization.XmlElementAttribute(Order=11)]
    public JeugdigenJeugdigeContactJournaals ContactJournaals {
        get {
            return this.contactJournaalsField;
        }
        set {
            this.contactJournaalsField = value;
        }
    }
    
    /// <opmerkingen/>
    [System.Xml.Serialization.XmlElementAttribute(Order=12)]
    public JeugdigenJeugdigeSamenvatting Samenvatting {
        get {
            return this.samenvattingField;
        }
        set {
            this.samenvattingField = value;
        }
    }
}

/// <opmerkingen/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.qnh.nl/xsd/caseload")]
public enum GeslachtType {
    
    /// <opmerkingen/>
    M,
    
    /// <opmerkingen/>
    V,
    
    /// <opmerkingen/>
    O,
}

/// <opmerkingen/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.qnh.nl/xsd/caseload")]
public partial class ArrayOfJeugdigenJeugdigeRelatieRelatie {
    
    private string soortField;
    
    private int idField;
    
    private string naamField;
    
    private GeslachtType geslachtField;
    
    private System.DateTime geboorteDatumField;
    
    private bool geboorteDatumFieldSpecified;
    
    private AdresType adressenField;
    
    private BereikbaarheidType bereikbaarheidField;
    
    /// <opmerkingen/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public string Soort {
        get {
            return this.soortField;
        }
        set {
            this.soortField = value;
        }
    }
    
    /// <opmerkingen/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public int Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <opmerkingen/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public string Naam {
        get {
            return this.naamField;
        }
        set {
            this.naamField = value;
        }
    }
    
    /// <opmerkingen/>
    [System.Xml.Serialization.XmlElementAttribute(Order=3)]
    public GeslachtType Geslacht {
        get {
            return this.geslachtField;
        }
        set {
            this.geslachtField = value;
        }
    }
    
    /// <opmerkingen/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=4)]
    public System.DateTime GeboorteDatum {
        get {
            return this.geboorteDatumField;
        }
        set {
            this.geboorteDatumField = value;
        }
    }
    
    /// <opmerkingen/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool GeboorteDatumSpecified {
        get {
            return this.geboorteDatumFieldSpecified;
        }
        set {
            this.geboorteDatumFieldSpecified = value;
        }
    }
    
    /// <opmerkingen/>
    [System.Xml.Serialization.XmlElementAttribute(Order=5)]
    public AdresType Adressen {
        get {
            return this.adressenField;
        }
        set {
            this.adressenField = value;
        }
    }
    
    /// <opmerkingen/>
    [System.Xml.Serialization.XmlElementAttribute(Order=6)]
    public BereikbaarheidType Bereikbaarheid {
        get {
            return this.bereikbaarheidField;
        }
        set {
            this.bereikbaarheidField = value;
        }
    }
}

/// <opmerkingen/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.qnh.nl/xsd/caseload")]
public partial class JeugdigenJeugdigeContactJournaals {
    
    private JeugdigenJeugdigeContactJournaalsContactJournaal[] contactJournaalField;
    
    private string[] textField;
    
    /// <opmerkingen/>
    [System.Xml.Serialization.XmlElementAttribute("ContactJournaal", Order=0)]
    public JeugdigenJeugdigeContactJournaalsContactJournaal[] ContactJournaal {
        get {
            return this.contactJournaalField;
        }
        set {
            this.contactJournaalField = value;
        }
    }
    
    /// <opmerkingen/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string[] Text {
        get {
            return this.textField;
        }
        set {
            this.textField = value;
        }
    }
}

/// <opmerkingen/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.qnh.nl/xsd/caseload")]
public partial class JeugdigenJeugdigeContactJournaalsContactJournaal {
    
    private int idField;
    
    private string inhoudField;
    
    private System.DateTime datumField;
    
    private string medewerkerField;
    
    private string omschrijvingField;
    
    /// <opmerkingen/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public int Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <opmerkingen/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public string Inhoud {
        get {
            return this.inhoudField;
        }
        set {
            this.inhoudField = value;
        }
    }
    
    /// <opmerkingen/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=2)]
    public System.DateTime Datum {
        get {
            return this.datumField;
        }
        set {
            this.datumField = value;
        }
    }
    
    /// <opmerkingen/>
    [System.Xml.Serialization.XmlElementAttribute(Order=3)]
    public string Medewerker {
        get {
            return this.medewerkerField;
        }
        set {
            this.medewerkerField = value;
        }
    }
    
    /// <opmerkingen/>
    [System.Xml.Serialization.XmlElementAttribute(Order=4)]
    public string Omschrijving {
        get {
            return this.omschrijvingField;
        }
        set {
            this.omschrijvingField = value;
        }
    }
}

/// <opmerkingen/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.qnh.nl/xsd/caseload")]
public partial class JeugdigenJeugdigeSamenvatting {
    
    private string gezagField;
    
    private string zorgField;
    
    private string beschikkingField;
    
    /// <opmerkingen/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public string Gezag {
        get {
            return this.gezagField;
        }
        set {
            this.gezagField = value;
        }
    }
    
    /// <opmerkingen/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public string Zorg {
        get {
            return this.zorgField;
        }
        set {
            this.zorgField = value;
        }
    }
    
    /// <opmerkingen/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public string Beschikking {
        get {
            return this.beschikkingField;
        }
        set {
            this.beschikkingField = value;
        }
    }
}
