//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18046
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.Phone.ServiceReference, version 3.7.0.0
// 
namespace QNHDemo.WP.ijMobile {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ijMobile.IJMobileSoap")]
    public interface IJMobileSoap {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/Login", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.IAsyncResult BeginLogin(string loginNaam, string wachtwoord, string deviceID, System.AsyncCallback callback, object asyncState);
        
        QNHDemo.WP.ijMobile.LoginResultaat EndLogin(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/GeefCaseLoad", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.IAsyncResult BeginGeefCaseLoad(string loginToken, System.AsyncCallback callback, object asyncState);
        
        QNHDemo.WP.ijMobile.CaseloadResult EndGeefCaseLoad(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/VoegContactJournaalToe", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.IAsyncResult BeginVoegContactJournaalToe(string loginToken, string onderwerp, string inhoud, int hulpverleningID, System.DateTime datum, System.AsyncCallback callback, object asyncState);
        
        QNHDemo.WP.ijMobile.SessionStatus EndVoegContactJournaalToe(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/VoegContactJournalenToe", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.IAsyncResult BeginVoegContactJournalenToe(string loginToken, QNHDemo.WP.ijMobile.ContactJournaal[] journalen, System.AsyncCallback callback, object asyncState);
        
        QNHDemo.WP.ijMobile.SessionStatus EndVoegContactJournalenToe(System.IAsyncResult result);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18046")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginResultaat : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string naamMedewerkerField;
        
        private LoginStatus statusField;
        
        private string tokenField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string NaamMedewerker {
            get {
                return this.naamMedewerkerField;
            }
            set {
                this.naamMedewerkerField = value;
                this.RaisePropertyChanged("NaamMedewerker");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public LoginStatus Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
                this.RaisePropertyChanged("Token");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18046")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum LoginStatus {
        
        /// <remarks/>
        Succes,
        
        /// <remarks/>
        ToestelGeblokkeerd,
        
        /// <remarks/>
        OngeldigeGegevens,
        
        /// <remarks/>
        GebruikerGeblokkeerd,
        
        /// <remarks/>
        GeneriekeFout,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18046")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ContactJournaal : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int hulpVerleningIdField;
        
        private string onderwerpField;
        
        private string inhoudField;
        
        private System.DateTime datumField;
        
        private int medewerkerIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int HulpVerleningId {
            get {
                return this.hulpVerleningIdField;
            }
            set {
                this.hulpVerleningIdField = value;
                this.RaisePropertyChanged("HulpVerleningId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Onderwerp {
            get {
                return this.onderwerpField;
            }
            set {
                this.onderwerpField = value;
                this.RaisePropertyChanged("Onderwerp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Inhoud {
            get {
                return this.inhoudField;
            }
            set {
                this.inhoudField = value;
                this.RaisePropertyChanged("Inhoud");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public System.DateTime Datum {
            get {
                return this.datumField;
            }
            set {
                this.datumField = value;
                this.RaisePropertyChanged("Datum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int MedewerkerID {
            get {
                return this.medewerkerIDField;
            }
            set {
                this.medewerkerIDField = value;
                this.RaisePropertyChanged("MedewerkerID");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18046")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.qnh.nl/xsd/caseload")]
    public partial class BereikbaarheidType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private BereikbaarheidTypeBereikbaar[] bereikbaarField;
        
        private string[] textField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Bereikbaar", Order=0)]
        public BereikbaarheidTypeBereikbaar[] Bereikbaar {
            get {
                return this.bereikbaarField;
            }
            set {
                this.bereikbaarField = value;
                this.RaisePropertyChanged("Bereikbaar");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
                this.RaisePropertyChanged("Text");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18046")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.qnh.nl/xsd/caseload")]
    public partial class BereikbaarheidTypeBereikbaar : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string soortField;
        
        private string waardeField;
        
        private string opmerkingenField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Soort {
            get {
                return this.soortField;
            }
            set {
                this.soortField = value;
                this.RaisePropertyChanged("Soort");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Waarde {
            get {
                return this.waardeField;
            }
            set {
                this.waardeField = value;
                this.RaisePropertyChanged("Waarde");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Opmerkingen {
            get {
                return this.opmerkingenField;
            }
            set {
                this.opmerkingenField = value;
                this.RaisePropertyChanged("Opmerkingen");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18046")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.qnh.nl/xsd/caseload")]
    public partial class AdresType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private AdresTypeAdres[] adresField;
        
        private string[] textField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Adres", Order=0)]
        public AdresTypeAdres[] Adres {
            get {
                return this.adresField;
            }
            set {
                this.adresField = value;
                this.RaisePropertyChanged("Adres");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
                this.RaisePropertyChanged("Text");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18046")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.qnh.nl/xsd/caseload")]
    public partial class AdresTypeAdres : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string straatField;
        
        private short huisNummerField;
        
        private string postcodeField;
        
        private string plaatsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Straat {
            get {
                return this.straatField;
            }
            set {
                this.straatField = value;
                this.RaisePropertyChanged("Straat");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public short HuisNummer {
            get {
                return this.huisNummerField;
            }
            set {
                this.huisNummerField = value;
                this.RaisePropertyChanged("HuisNummer");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Postcode {
            get {
                return this.postcodeField;
            }
            set {
                this.postcodeField = value;
                this.RaisePropertyChanged("Postcode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Plaats {
            get {
                return this.plaatsField;
            }
            set {
                this.plaatsField = value;
                this.RaisePropertyChanged("Plaats");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18046")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CaseloadResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private SessionStatus statusField;
        
        private JeugdigenJeugdige[] jeugdigenField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public SessionStatus Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Jeugdige", Namespace="http://www.qnh.nl/xsd/caseload", IsNullable=false)]
        public JeugdigenJeugdige[] Jeugdigen {
            get {
                return this.jeugdigenField;
            }
            set {
                this.jeugdigenField = value;
                this.RaisePropertyChanged("Jeugdigen");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18046")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum SessionStatus {
        
        /// <remarks/>
        Ok,
        
        /// <remarks/>
        Verlopen,
        
        /// <remarks/>
        Ongeldig,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18046")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.qnh.nl/xsd/caseload")]
    public partial class JeugdigenJeugdige : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private int hulpverleningIdField;
        
        private string typeHulpverleningField;
        
        private string isEersteContactPersoonField;
        
        private string naamField;
        
        private GeslachtType geslachtField;
        
        private System.DateTime geboorteDatumField;
        
        private AdresType adressenField;
        
        private BereikbaarheidType bereikbaarheidField;
        
        private string aantekeningenField;
        
        private ArrayOfJeugdigenJeugdigeRelatieRelatie[] relatiesField;
        
        private JeugdigenJeugdigeContactJournaals contactJournaalsField;
        
        private JeugdigenJeugdigeSamenvatting samenvattingField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int HulpverleningId {
            get {
                return this.hulpverleningIdField;
            }
            set {
                this.hulpverleningIdField = value;
                this.RaisePropertyChanged("HulpverleningId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string TypeHulpverlening {
            get {
                return this.typeHulpverleningField;
            }
            set {
                this.typeHulpverleningField = value;
                this.RaisePropertyChanged("TypeHulpverlening");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string IsEersteContactPersoon {
            get {
                return this.isEersteContactPersoonField;
            }
            set {
                this.isEersteContactPersoonField = value;
                this.RaisePropertyChanged("IsEersteContactPersoon");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Naam {
            get {
                return this.naamField;
            }
            set {
                this.naamField = value;
                this.RaisePropertyChanged("Naam");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public GeslachtType Geslacht {
            get {
                return this.geslachtField;
            }
            set {
                this.geslachtField = value;
                this.RaisePropertyChanged("Geslacht");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=6)]
        public System.DateTime GeboorteDatum {
            get {
                return this.geboorteDatumField;
            }
            set {
                this.geboorteDatumField = value;
                this.RaisePropertyChanged("GeboorteDatum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public AdresType Adressen {
            get {
                return this.adressenField;
            }
            set {
                this.adressenField = value;
                this.RaisePropertyChanged("Adressen");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public BereikbaarheidType Bereikbaarheid {
            get {
                return this.bereikbaarheidField;
            }
            set {
                this.bereikbaarheidField = value;
                this.RaisePropertyChanged("Bereikbaarheid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string Aantekeningen {
            get {
                return this.aantekeningenField;
            }
            set {
                this.aantekeningenField = value;
                this.RaisePropertyChanged("Aantekeningen");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=10)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Relatie", IsNullable=false)]
        public ArrayOfJeugdigenJeugdigeRelatieRelatie[] Relaties {
            get {
                return this.relatiesField;
            }
            set {
                this.relatiesField = value;
                this.RaisePropertyChanged("Relaties");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public JeugdigenJeugdigeContactJournaals ContactJournaals {
            get {
                return this.contactJournaalsField;
            }
            set {
                this.contactJournaalsField = value;
                this.RaisePropertyChanged("ContactJournaals");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public JeugdigenJeugdigeSamenvatting Samenvatting {
            get {
                return this.samenvattingField;
            }
            set {
                this.samenvattingField = value;
                this.RaisePropertyChanged("Samenvatting");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18046")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.qnh.nl/xsd/caseload")]
    public enum GeslachtType {
        
        /// <remarks/>
        M,
        
        /// <remarks/>
        V,
        
        /// <remarks/>
        O,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18046")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.qnh.nl/xsd/caseload")]
    public partial class ArrayOfJeugdigenJeugdigeRelatieRelatie : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string soortField;
        
        private int idField;
        
        private string naamField;
        
        private GeslachtType geslachtField;
        
        private System.DateTime geboorteDatumField;
        
        private bool geboorteDatumFieldSpecified;
        
        private AdresType adressenField;
        
        private BereikbaarheidType bereikbaarheidField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Soort {
            get {
                return this.soortField;
            }
            set {
                this.soortField = value;
                this.RaisePropertyChanged("Soort");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Naam {
            get {
                return this.naamField;
            }
            set {
                this.naamField = value;
                this.RaisePropertyChanged("Naam");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public GeslachtType Geslacht {
            get {
                return this.geslachtField;
            }
            set {
                this.geslachtField = value;
                this.RaisePropertyChanged("Geslacht");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=4)]
        public System.DateTime GeboorteDatum {
            get {
                return this.geboorteDatumField;
            }
            set {
                this.geboorteDatumField = value;
                this.RaisePropertyChanged("GeboorteDatum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool GeboorteDatumSpecified {
            get {
                return this.geboorteDatumFieldSpecified;
            }
            set {
                this.geboorteDatumFieldSpecified = value;
                this.RaisePropertyChanged("GeboorteDatumSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public AdresType Adressen {
            get {
                return this.adressenField;
            }
            set {
                this.adressenField = value;
                this.RaisePropertyChanged("Adressen");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public BereikbaarheidType Bereikbaarheid {
            get {
                return this.bereikbaarheidField;
            }
            set {
                this.bereikbaarheidField = value;
                this.RaisePropertyChanged("Bereikbaarheid");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18046")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.qnh.nl/xsd/caseload")]
    public partial class JeugdigenJeugdigeContactJournaals : object, System.ComponentModel.INotifyPropertyChanged {
        
        private JeugdigenJeugdigeContactJournaalsContactJournaal[] contactJournaalField;
        
        private string[] textField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ContactJournaal", Order=0)]
        public JeugdigenJeugdigeContactJournaalsContactJournaal[] ContactJournaal {
            get {
                return this.contactJournaalField;
            }
            set {
                this.contactJournaalField = value;
                this.RaisePropertyChanged("ContactJournaal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
                this.RaisePropertyChanged("Text");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18046")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.qnh.nl/xsd/caseload")]
    public partial class JeugdigenJeugdigeContactJournaalsContactJournaal : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private string inhoudField;
        
        private System.DateTime datumField;
        
        private string medewerkerField;
        
        private string omschrijvingField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Inhoud {
            get {
                return this.inhoudField;
            }
            set {
                this.inhoudField = value;
                this.RaisePropertyChanged("Inhoud");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=2)]
        public System.DateTime Datum {
            get {
                return this.datumField;
            }
            set {
                this.datumField = value;
                this.RaisePropertyChanged("Datum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Medewerker {
            get {
                return this.medewerkerField;
            }
            set {
                this.medewerkerField = value;
                this.RaisePropertyChanged("Medewerker");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Omschrijving {
            get {
                return this.omschrijvingField;
            }
            set {
                this.omschrijvingField = value;
                this.RaisePropertyChanged("Omschrijving");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18046")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.qnh.nl/xsd/caseload")]
    public partial class JeugdigenJeugdigeSamenvatting : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string gezagField;
        
        private string zorgField;
        
        private string beschikkingField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Gezag {
            get {
                return this.gezagField;
            }
            set {
                this.gezagField = value;
                this.RaisePropertyChanged("Gezag");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Zorg {
            get {
                return this.zorgField;
            }
            set {
                this.zorgField = value;
                this.RaisePropertyChanged("Zorg");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Beschikking {
            get {
                return this.beschikkingField;
            }
            set {
                this.beschikkingField = value;
                this.RaisePropertyChanged("Beschikking");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IJMobileSoapChannel : QNHDemo.WP.ijMobile.IJMobileSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LoginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public LoginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public QNHDemo.WP.ijMobile.LoginResultaat Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((QNHDemo.WP.ijMobile.LoginResultaat)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GeefCaseLoadCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GeefCaseLoadCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public QNHDemo.WP.ijMobile.CaseloadResult Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((QNHDemo.WP.ijMobile.CaseloadResult)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VoegContactJournaalToeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public VoegContactJournaalToeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public QNHDemo.WP.ijMobile.SessionStatus Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((QNHDemo.WP.ijMobile.SessionStatus)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VoegContactJournalenToeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public VoegContactJournalenToeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public QNHDemo.WP.ijMobile.SessionStatus Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((QNHDemo.WP.ijMobile.SessionStatus)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class JMobileSoapClient : System.ServiceModel.ClientBase<QNHDemo.WP.ijMobile.IJMobileSoap>, QNHDemo.WP.ijMobile.IJMobileSoap {
        
        private BeginOperationDelegate onBeginLoginDelegate;
        
        private EndOperationDelegate onEndLoginDelegate;
        
        private System.Threading.SendOrPostCallback onLoginCompletedDelegate;
        
        private BeginOperationDelegate onBeginGeefCaseLoadDelegate;
        
        private EndOperationDelegate onEndGeefCaseLoadDelegate;
        
        private System.Threading.SendOrPostCallback onGeefCaseLoadCompletedDelegate;
        
        private BeginOperationDelegate onBeginVoegContactJournaalToeDelegate;
        
        private EndOperationDelegate onEndVoegContactJournaalToeDelegate;
        
        private System.Threading.SendOrPostCallback onVoegContactJournaalToeCompletedDelegate;
        
        private BeginOperationDelegate onBeginVoegContactJournalenToeDelegate;
        
        private EndOperationDelegate onEndVoegContactJournalenToeDelegate;
        
        private System.Threading.SendOrPostCallback onVoegContactJournalenToeCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public JMobileSoapClient() {
        }
        
        public JMobileSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public JMobileSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public JMobileSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public JMobileSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<LoginCompletedEventArgs> LoginCompleted;
        
        public event System.EventHandler<GeefCaseLoadCompletedEventArgs> GeefCaseLoadCompleted;
        
        public event System.EventHandler<VoegContactJournaalToeCompletedEventArgs> VoegContactJournaalToeCompleted;
        
        public event System.EventHandler<VoegContactJournalenToeCompletedEventArgs> VoegContactJournalenToeCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult QNHDemo.WP.ijMobile.IJMobileSoap.BeginLogin(string loginNaam, string wachtwoord, string deviceID, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginLogin(loginNaam, wachtwoord, deviceID, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        QNHDemo.WP.ijMobile.LoginResultaat QNHDemo.WP.ijMobile.IJMobileSoap.EndLogin(System.IAsyncResult result) {
            return base.Channel.EndLogin(result);
        }
        
        private System.IAsyncResult OnBeginLogin(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string loginNaam = ((string)(inValues[0]));
            string wachtwoord = ((string)(inValues[1]));
            string deviceID = ((string)(inValues[2]));
            return ((QNHDemo.WP.ijMobile.IJMobileSoap)(this)).BeginLogin(loginNaam, wachtwoord, deviceID, callback, asyncState);
        }
        
        private object[] OnEndLogin(System.IAsyncResult result) {
            QNHDemo.WP.ijMobile.LoginResultaat retVal = ((QNHDemo.WP.ijMobile.IJMobileSoap)(this)).EndLogin(result);
            return new object[] {
                    retVal};
        }
        
        private void OnLoginCompleted(object state) {
            if ((this.LoginCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.LoginCompleted(this, new LoginCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void LoginAsync(string loginNaam, string wachtwoord, string deviceID) {
            this.LoginAsync(loginNaam, wachtwoord, deviceID, null);
        }
        
        public void LoginAsync(string loginNaam, string wachtwoord, string deviceID, object userState) {
            if ((this.onBeginLoginDelegate == null)) {
                this.onBeginLoginDelegate = new BeginOperationDelegate(this.OnBeginLogin);
            }
            if ((this.onEndLoginDelegate == null)) {
                this.onEndLoginDelegate = new EndOperationDelegate(this.OnEndLogin);
            }
            if ((this.onLoginCompletedDelegate == null)) {
                this.onLoginCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnLoginCompleted);
            }
            base.InvokeAsync(this.onBeginLoginDelegate, new object[] {
                        loginNaam,
                        wachtwoord,
                        deviceID}, this.onEndLoginDelegate, this.onLoginCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult QNHDemo.WP.ijMobile.IJMobileSoap.BeginGeefCaseLoad(string loginToken, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGeefCaseLoad(loginToken, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        QNHDemo.WP.ijMobile.CaseloadResult QNHDemo.WP.ijMobile.IJMobileSoap.EndGeefCaseLoad(System.IAsyncResult result) {
            return base.Channel.EndGeefCaseLoad(result);
        }
        
        private System.IAsyncResult OnBeginGeefCaseLoad(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string loginToken = ((string)(inValues[0]));
            return ((QNHDemo.WP.ijMobile.IJMobileSoap)(this)).BeginGeefCaseLoad(loginToken, callback, asyncState);
        }
        
        private object[] OnEndGeefCaseLoad(System.IAsyncResult result) {
            QNHDemo.WP.ijMobile.CaseloadResult retVal = ((QNHDemo.WP.ijMobile.IJMobileSoap)(this)).EndGeefCaseLoad(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGeefCaseLoadCompleted(object state) {
            if ((this.GeefCaseLoadCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GeefCaseLoadCompleted(this, new GeefCaseLoadCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GeefCaseLoadAsync(string loginToken) {
            this.GeefCaseLoadAsync(loginToken, null);
        }
        
        public void GeefCaseLoadAsync(string loginToken, object userState) {
            if ((this.onBeginGeefCaseLoadDelegate == null)) {
                this.onBeginGeefCaseLoadDelegate = new BeginOperationDelegate(this.OnBeginGeefCaseLoad);
            }
            if ((this.onEndGeefCaseLoadDelegate == null)) {
                this.onEndGeefCaseLoadDelegate = new EndOperationDelegate(this.OnEndGeefCaseLoad);
            }
            if ((this.onGeefCaseLoadCompletedDelegate == null)) {
                this.onGeefCaseLoadCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGeefCaseLoadCompleted);
            }
            base.InvokeAsync(this.onBeginGeefCaseLoadDelegate, new object[] {
                        loginToken}, this.onEndGeefCaseLoadDelegate, this.onGeefCaseLoadCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult QNHDemo.WP.ijMobile.IJMobileSoap.BeginVoegContactJournaalToe(string loginToken, string onderwerp, string inhoud, int hulpverleningID, System.DateTime datum, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginVoegContactJournaalToe(loginToken, onderwerp, inhoud, hulpverleningID, datum, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        QNHDemo.WP.ijMobile.SessionStatus QNHDemo.WP.ijMobile.IJMobileSoap.EndVoegContactJournaalToe(System.IAsyncResult result) {
            return base.Channel.EndVoegContactJournaalToe(result);
        }
        
        private System.IAsyncResult OnBeginVoegContactJournaalToe(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string loginToken = ((string)(inValues[0]));
            string onderwerp = ((string)(inValues[1]));
            string inhoud = ((string)(inValues[2]));
            int hulpverleningID = ((int)(inValues[3]));
            System.DateTime datum = ((System.DateTime)(inValues[4]));
            return ((QNHDemo.WP.ijMobile.IJMobileSoap)(this)).BeginVoegContactJournaalToe(loginToken, onderwerp, inhoud, hulpverleningID, datum, callback, asyncState);
        }
        
        private object[] OnEndVoegContactJournaalToe(System.IAsyncResult result) {
            QNHDemo.WP.ijMobile.SessionStatus retVal = ((QNHDemo.WP.ijMobile.IJMobileSoap)(this)).EndVoegContactJournaalToe(result);
            return new object[] {
                    retVal};
        }
        
        private void OnVoegContactJournaalToeCompleted(object state) {
            if ((this.VoegContactJournaalToeCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.VoegContactJournaalToeCompleted(this, new VoegContactJournaalToeCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void VoegContactJournaalToeAsync(string loginToken, string onderwerp, string inhoud, int hulpverleningID, System.DateTime datum) {
            this.VoegContactJournaalToeAsync(loginToken, onderwerp, inhoud, hulpverleningID, datum, null);
        }
        
        public void VoegContactJournaalToeAsync(string loginToken, string onderwerp, string inhoud, int hulpverleningID, System.DateTime datum, object userState) {
            if ((this.onBeginVoegContactJournaalToeDelegate == null)) {
                this.onBeginVoegContactJournaalToeDelegate = new BeginOperationDelegate(this.OnBeginVoegContactJournaalToe);
            }
            if ((this.onEndVoegContactJournaalToeDelegate == null)) {
                this.onEndVoegContactJournaalToeDelegate = new EndOperationDelegate(this.OnEndVoegContactJournaalToe);
            }
            if ((this.onVoegContactJournaalToeCompletedDelegate == null)) {
                this.onVoegContactJournaalToeCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnVoegContactJournaalToeCompleted);
            }
            base.InvokeAsync(this.onBeginVoegContactJournaalToeDelegate, new object[] {
                        loginToken,
                        onderwerp,
                        inhoud,
                        hulpverleningID,
                        datum}, this.onEndVoegContactJournaalToeDelegate, this.onVoegContactJournaalToeCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult QNHDemo.WP.ijMobile.IJMobileSoap.BeginVoegContactJournalenToe(string loginToken, QNHDemo.WP.ijMobile.ContactJournaal[] journalen, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginVoegContactJournalenToe(loginToken, journalen, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        QNHDemo.WP.ijMobile.SessionStatus QNHDemo.WP.ijMobile.IJMobileSoap.EndVoegContactJournalenToe(System.IAsyncResult result) {
            return base.Channel.EndVoegContactJournalenToe(result);
        }
        
        private System.IAsyncResult OnBeginVoegContactJournalenToe(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string loginToken = ((string)(inValues[0]));
            QNHDemo.WP.ijMobile.ContactJournaal[] journalen = ((QNHDemo.WP.ijMobile.ContactJournaal[])(inValues[1]));
            return ((QNHDemo.WP.ijMobile.IJMobileSoap)(this)).BeginVoegContactJournalenToe(loginToken, journalen, callback, asyncState);
        }
        
        private object[] OnEndVoegContactJournalenToe(System.IAsyncResult result) {
            QNHDemo.WP.ijMobile.SessionStatus retVal = ((QNHDemo.WP.ijMobile.IJMobileSoap)(this)).EndVoegContactJournalenToe(result);
            return new object[] {
                    retVal};
        }
        
        private void OnVoegContactJournalenToeCompleted(object state) {
            if ((this.VoegContactJournalenToeCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.VoegContactJournalenToeCompleted(this, new VoegContactJournalenToeCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void VoegContactJournalenToeAsync(string loginToken, QNHDemo.WP.ijMobile.ContactJournaal[] journalen) {
            this.VoegContactJournalenToeAsync(loginToken, journalen, null);
        }
        
        public void VoegContactJournalenToeAsync(string loginToken, QNHDemo.WP.ijMobile.ContactJournaal[] journalen, object userState) {
            if ((this.onBeginVoegContactJournalenToeDelegate == null)) {
                this.onBeginVoegContactJournalenToeDelegate = new BeginOperationDelegate(this.OnBeginVoegContactJournalenToe);
            }
            if ((this.onEndVoegContactJournalenToeDelegate == null)) {
                this.onEndVoegContactJournalenToeDelegate = new EndOperationDelegate(this.OnEndVoegContactJournalenToe);
            }
            if ((this.onVoegContactJournalenToeCompletedDelegate == null)) {
                this.onVoegContactJournalenToeCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnVoegContactJournalenToeCompleted);
            }
            base.InvokeAsync(this.onBeginVoegContactJournalenToeDelegate, new object[] {
                        loginToken,
                        journalen}, this.onEndVoegContactJournalenToeDelegate, this.onVoegContactJournalenToeCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override QNHDemo.WP.ijMobile.IJMobileSoap CreateChannel() {
            return new JMobileSoapClientChannel(this);
        }
        
        private class JMobileSoapClientChannel : ChannelBase<QNHDemo.WP.ijMobile.IJMobileSoap>, QNHDemo.WP.ijMobile.IJMobileSoap {
            
            public JMobileSoapClientChannel(System.ServiceModel.ClientBase<QNHDemo.WP.ijMobile.IJMobileSoap> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginLogin(string loginNaam, string wachtwoord, string deviceID, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[3];
                _args[0] = loginNaam;
                _args[1] = wachtwoord;
                _args[2] = deviceID;
                System.IAsyncResult _result = base.BeginInvoke("Login", _args, callback, asyncState);
                return _result;
            }
            
            public QNHDemo.WP.ijMobile.LoginResultaat EndLogin(System.IAsyncResult result) {
                object[] _args = new object[0];
                QNHDemo.WP.ijMobile.LoginResultaat _result = ((QNHDemo.WP.ijMobile.LoginResultaat)(base.EndInvoke("Login", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGeefCaseLoad(string loginToken, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = loginToken;
                System.IAsyncResult _result = base.BeginInvoke("GeefCaseLoad", _args, callback, asyncState);
                return _result;
            }
            
            public QNHDemo.WP.ijMobile.CaseloadResult EndGeefCaseLoad(System.IAsyncResult result) {
                object[] _args = new object[0];
                QNHDemo.WP.ijMobile.CaseloadResult _result = ((QNHDemo.WP.ijMobile.CaseloadResult)(base.EndInvoke("GeefCaseLoad", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginVoegContactJournaalToe(string loginToken, string onderwerp, string inhoud, int hulpverleningID, System.DateTime datum, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[5];
                _args[0] = loginToken;
                _args[1] = onderwerp;
                _args[2] = inhoud;
                _args[3] = hulpverleningID;
                _args[4] = datum;
                System.IAsyncResult _result = base.BeginInvoke("VoegContactJournaalToe", _args, callback, asyncState);
                return _result;
            }
            
            public QNHDemo.WP.ijMobile.SessionStatus EndVoegContactJournaalToe(System.IAsyncResult result) {
                object[] _args = new object[0];
                QNHDemo.WP.ijMobile.SessionStatus _result = ((QNHDemo.WP.ijMobile.SessionStatus)(base.EndInvoke("VoegContactJournaalToe", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginVoegContactJournalenToe(string loginToken, QNHDemo.WP.ijMobile.ContactJournaal[] journalen, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[2];
                _args[0] = loginToken;
                _args[1] = journalen;
                System.IAsyncResult _result = base.BeginInvoke("VoegContactJournalenToe", _args, callback, asyncState);
                return _result;
            }
            
            public QNHDemo.WP.ijMobile.SessionStatus EndVoegContactJournalenToe(System.IAsyncResult result) {
                object[] _args = new object[0];
                QNHDemo.WP.ijMobile.SessionStatus _result = ((QNHDemo.WP.ijMobile.SessionStatus)(base.EndInvoke("VoegContactJournalenToe", _args, result)));
                return _result;
            }
        }
    }
}
