//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18046
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QNHDemo.WP7.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IJMobileSoap")]
    public interface IJMobileSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Login", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        QNHDemo.WP7.ServiceReference1.LoginResultaat Login(string loginNaam, string wachtwoord, string deviceID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GeefCaseLoad", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        QNHDemo.WP7.ServiceReference1.CaseloadResult GeefCaseLoad(string loginToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VoegContactJournaalToe", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        QNHDemo.WP7.ServiceReference1.SessionStatus VoegContactJournaalToe(string loginToken, string onderwerp, string inhoud, int hulpverleningID, System.DateTime datum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VoegContactJournalenToe", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        QNHDemo.WP7.ServiceReference1.SessionStatus VoegContactJournalenToe(string loginToken, QNHDemo.WP7.ServiceReference1.ContactJournaal[] journalen);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18046")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginResultaat : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string naamMedewerkerField;
        
        private LoginStatus statusField;
        
        private string tokenField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string NaamMedewerker {
            get {
                return this.naamMedewerkerField;
            }
            set {
                this.naamMedewerkerField = value;
                this.RaisePropertyChanged("NaamMedewerker");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public LoginStatus Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
                this.RaisePropertyChanged("Token");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18046")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum LoginStatus {
        
        /// <remarks/>
        Succes,
        
        /// <remarks/>
        ToestelGeblokkeerd,
        
        /// <remarks/>
        OngeldigeGegevens,
        
        /// <remarks/>
        GebruikerGeblokkeerd,
        
        /// <remarks/>
        GeneriekeFout,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18046")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ContactJournaal : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int hulpVerleningIdField;
        
        private string onderwerpField;
        
        private string inhoudField;
        
        private System.DateTime datumField;
        
        private int medewerkerIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int HulpVerleningId {
            get {
                return this.hulpVerleningIdField;
            }
            set {
                this.hulpVerleningIdField = value;
                this.RaisePropertyChanged("HulpVerleningId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Onderwerp {
            get {
                return this.onderwerpField;
            }
            set {
                this.onderwerpField = value;
                this.RaisePropertyChanged("Onderwerp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Inhoud {
            get {
                return this.inhoudField;
            }
            set {
                this.inhoudField = value;
                this.RaisePropertyChanged("Inhoud");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public System.DateTime Datum {
            get {
                return this.datumField;
            }
            set {
                this.datumField = value;
                this.RaisePropertyChanged("Datum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int MedewerkerID {
            get {
                return this.medewerkerIDField;
            }
            set {
                this.medewerkerIDField = value;
                this.RaisePropertyChanged("MedewerkerID");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18046")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.qnh.nl/xsd/caseload")]
    public partial class BereikbaarheidType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private BereikbaarheidTypeBereikbaar[] bereikbaarField;
        
        private string[] textField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Bereikbaar", Order=0)]
        public BereikbaarheidTypeBereikbaar[] Bereikbaar {
            get {
                return this.bereikbaarField;
            }
            set {
                this.bereikbaarField = value;
                this.RaisePropertyChanged("Bereikbaar");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
                this.RaisePropertyChanged("Text");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18046")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.qnh.nl/xsd/caseload")]
    public partial class BereikbaarheidTypeBereikbaar : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string soortField;
        
        private string waardeField;
        
        private string opmerkingenField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Soort {
            get {
                return this.soortField;
            }
            set {
                this.soortField = value;
                this.RaisePropertyChanged("Soort");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Waarde {
            get {
                return this.waardeField;
            }
            set {
                this.waardeField = value;
                this.RaisePropertyChanged("Waarde");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Opmerkingen {
            get {
                return this.opmerkingenField;
            }
            set {
                this.opmerkingenField = value;
                this.RaisePropertyChanged("Opmerkingen");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18046")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.qnh.nl/xsd/caseload")]
    public partial class AdresType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private AdresTypeAdres[] adresField;
        
        private string[] textField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Adres", Order=0)]
        public AdresTypeAdres[] Adres {
            get {
                return this.adresField;
            }
            set {
                this.adresField = value;
                this.RaisePropertyChanged("Adres");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
                this.RaisePropertyChanged("Text");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18046")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.qnh.nl/xsd/caseload")]
    public partial class AdresTypeAdres : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string straatField;
        
        private short huisNummerField;
        
        private string postcodeField;
        
        private string plaatsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Straat {
            get {
                return this.straatField;
            }
            set {
                this.straatField = value;
                this.RaisePropertyChanged("Straat");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public short HuisNummer {
            get {
                return this.huisNummerField;
            }
            set {
                this.huisNummerField = value;
                this.RaisePropertyChanged("HuisNummer");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Postcode {
            get {
                return this.postcodeField;
            }
            set {
                this.postcodeField = value;
                this.RaisePropertyChanged("Postcode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Plaats {
            get {
                return this.plaatsField;
            }
            set {
                this.plaatsField = value;
                this.RaisePropertyChanged("Plaats");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18046")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CaseloadResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private SessionStatus statusField;
        
        private JeugdigenJeugdige[] jeugdigenField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public SessionStatus Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Jeugdige", Namespace="http://www.qnh.nl/xsd/caseload", IsNullable=false)]
        public JeugdigenJeugdige[] Jeugdigen {
            get {
                return this.jeugdigenField;
            }
            set {
                this.jeugdigenField = value;
                this.RaisePropertyChanged("Jeugdigen");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18046")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum SessionStatus {
        
        /// <remarks/>
        Ok,
        
        /// <remarks/>
        Verlopen,
        
        /// <remarks/>
        Ongeldig,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18046")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.qnh.nl/xsd/caseload")]
    public partial class JeugdigenJeugdige : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private int hulpverleningIdField;
        
        private string typeHulpverleningField;
        
        private string isEersteContactPersoonField;
        
        private string naamField;
        
        private GeslachtType geslachtField;
        
        private System.DateTime geboorteDatumField;
        
        private AdresType adressenField;
        
        private BereikbaarheidType bereikbaarheidField;
        
        private string aantekeningenField;
        
        private ArrayOfJeugdigenJeugdigeRelatieRelatie[] relatiesField;
        
        private JeugdigenJeugdigeContactJournaals contactJournaalsField;
        
        private JeugdigenJeugdigeSamenvatting samenvattingField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int HulpverleningId {
            get {
                return this.hulpverleningIdField;
            }
            set {
                this.hulpverleningIdField = value;
                this.RaisePropertyChanged("HulpverleningId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string TypeHulpverlening {
            get {
                return this.typeHulpverleningField;
            }
            set {
                this.typeHulpverleningField = value;
                this.RaisePropertyChanged("TypeHulpverlening");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string IsEersteContactPersoon {
            get {
                return this.isEersteContactPersoonField;
            }
            set {
                this.isEersteContactPersoonField = value;
                this.RaisePropertyChanged("IsEersteContactPersoon");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Naam {
            get {
                return this.naamField;
            }
            set {
                this.naamField = value;
                this.RaisePropertyChanged("Naam");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public GeslachtType Geslacht {
            get {
                return this.geslachtField;
            }
            set {
                this.geslachtField = value;
                this.RaisePropertyChanged("Geslacht");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=6)]
        public System.DateTime GeboorteDatum {
            get {
                return this.geboorteDatumField;
            }
            set {
                this.geboorteDatumField = value;
                this.RaisePropertyChanged("GeboorteDatum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public AdresType Adressen {
            get {
                return this.adressenField;
            }
            set {
                this.adressenField = value;
                this.RaisePropertyChanged("Adressen");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public BereikbaarheidType Bereikbaarheid {
            get {
                return this.bereikbaarheidField;
            }
            set {
                this.bereikbaarheidField = value;
                this.RaisePropertyChanged("Bereikbaarheid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string Aantekeningen {
            get {
                return this.aantekeningenField;
            }
            set {
                this.aantekeningenField = value;
                this.RaisePropertyChanged("Aantekeningen");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=10)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Relatie", IsNullable=false)]
        public ArrayOfJeugdigenJeugdigeRelatieRelatie[] Relaties {
            get {
                return this.relatiesField;
            }
            set {
                this.relatiesField = value;
                this.RaisePropertyChanged("Relaties");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public JeugdigenJeugdigeContactJournaals ContactJournaals {
            get {
                return this.contactJournaalsField;
            }
            set {
                this.contactJournaalsField = value;
                this.RaisePropertyChanged("ContactJournaals");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public JeugdigenJeugdigeSamenvatting Samenvatting {
            get {
                return this.samenvattingField;
            }
            set {
                this.samenvattingField = value;
                this.RaisePropertyChanged("Samenvatting");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18046")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.qnh.nl/xsd/caseload")]
    public enum GeslachtType {
        
        /// <remarks/>
        M,
        
        /// <remarks/>
        V,
        
        /// <remarks/>
        O,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18046")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.qnh.nl/xsd/caseload")]
    public partial class ArrayOfJeugdigenJeugdigeRelatieRelatie : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string soortField;
        
        private int idField;
        
        private string naamField;
        
        private GeslachtType geslachtField;
        
        private System.DateTime geboorteDatumField;
        
        private bool geboorteDatumFieldSpecified;
        
        private AdresType adressenField;
        
        private BereikbaarheidType bereikbaarheidField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Soort {
            get {
                return this.soortField;
            }
            set {
                this.soortField = value;
                this.RaisePropertyChanged("Soort");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Naam {
            get {
                return this.naamField;
            }
            set {
                this.naamField = value;
                this.RaisePropertyChanged("Naam");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public GeslachtType Geslacht {
            get {
                return this.geslachtField;
            }
            set {
                this.geslachtField = value;
                this.RaisePropertyChanged("Geslacht");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=4)]
        public System.DateTime GeboorteDatum {
            get {
                return this.geboorteDatumField;
            }
            set {
                this.geboorteDatumField = value;
                this.RaisePropertyChanged("GeboorteDatum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool GeboorteDatumSpecified {
            get {
                return this.geboorteDatumFieldSpecified;
            }
            set {
                this.geboorteDatumFieldSpecified = value;
                this.RaisePropertyChanged("GeboorteDatumSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public AdresType Adressen {
            get {
                return this.adressenField;
            }
            set {
                this.adressenField = value;
                this.RaisePropertyChanged("Adressen");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public BereikbaarheidType Bereikbaarheid {
            get {
                return this.bereikbaarheidField;
            }
            set {
                this.bereikbaarheidField = value;
                this.RaisePropertyChanged("Bereikbaarheid");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18046")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.qnh.nl/xsd/caseload")]
    public partial class JeugdigenJeugdigeContactJournaals : object, System.ComponentModel.INotifyPropertyChanged {
        
        private JeugdigenJeugdigeContactJournaalsContactJournaal[] contactJournaalField;
        
        private string[] textField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ContactJournaal", Order=0)]
        public JeugdigenJeugdigeContactJournaalsContactJournaal[] ContactJournaal {
            get {
                return this.contactJournaalField;
            }
            set {
                this.contactJournaalField = value;
                this.RaisePropertyChanged("ContactJournaal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
                this.RaisePropertyChanged("Text");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18046")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.qnh.nl/xsd/caseload")]
    public partial class JeugdigenJeugdigeContactJournaalsContactJournaal : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private string inhoudField;
        
        private System.DateTime datumField;
        
        private string medewerkerField;
        
        private string omschrijvingField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Inhoud {
            get {
                return this.inhoudField;
            }
            set {
                this.inhoudField = value;
                this.RaisePropertyChanged("Inhoud");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=2)]
        public System.DateTime Datum {
            get {
                return this.datumField;
            }
            set {
                this.datumField = value;
                this.RaisePropertyChanged("Datum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Medewerker {
            get {
                return this.medewerkerField;
            }
            set {
                this.medewerkerField = value;
                this.RaisePropertyChanged("Medewerker");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Omschrijving {
            get {
                return this.omschrijvingField;
            }
            set {
                this.omschrijvingField = value;
                this.RaisePropertyChanged("Omschrijving");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18046")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.qnh.nl/xsd/caseload")]
    public partial class JeugdigenJeugdigeSamenvatting : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string gezagField;
        
        private string zorgField;
        
        private string beschikkingField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Gezag {
            get {
                return this.gezagField;
            }
            set {
                this.gezagField = value;
                this.RaisePropertyChanged("Gezag");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Zorg {
            get {
                return this.zorgField;
            }
            set {
                this.zorgField = value;
                this.RaisePropertyChanged("Zorg");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Beschikking {
            get {
                return this.beschikkingField;
            }
            set {
                this.beschikkingField = value;
                this.RaisePropertyChanged("Beschikking");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IJMobileSoapChannel : QNHDemo.WP7.ServiceReference1.IJMobileSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class JMobileSoapClient : System.ServiceModel.ClientBase<QNHDemo.WP7.ServiceReference1.IJMobileSoap>, QNHDemo.WP7.ServiceReference1.IJMobileSoap {
        
        public JMobileSoapClient() {
        }
        
        public JMobileSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public JMobileSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public JMobileSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public JMobileSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public QNHDemo.WP7.ServiceReference1.LoginResultaat Login(string loginNaam, string wachtwoord, string deviceID) {
            return base.Channel.Login(loginNaam, wachtwoord, deviceID);
        }
        
        public QNHDemo.WP7.ServiceReference1.CaseloadResult GeefCaseLoad(string loginToken) {
            return base.Channel.GeefCaseLoad(loginToken);
        }
        
        public QNHDemo.WP7.ServiceReference1.SessionStatus VoegContactJournaalToe(string loginToken, string onderwerp, string inhoud, int hulpverleningID, System.DateTime datum) {
            return base.Channel.VoegContactJournaalToe(loginToken, onderwerp, inhoud, hulpverleningID, datum);
        }
        
        public QNHDemo.WP7.ServiceReference1.SessionStatus VoegContactJournalenToe(string loginToken, QNHDemo.WP7.ServiceReference1.ContactJournaal[] journalen) {
            return base.Channel.VoegContactJournalenToe(loginToken, journalen);
        }
    }
}
