//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18046
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QNHDemo.Android.ijmobile.bjzlimburg.nl {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="IJMobileSoap", Namespace="http://tempuri.org/")]
    public partial class IJMobile : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public IJMobile() {
            this.Url = "https://bjlwb003.bjzlimburg.lan/ONTW/ijmobile.asmx";
        }
        
        public IJMobile(string url) {
            this.Url = url;
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Login", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public LoginResultaat Login(string loginNaam, string wachtwoord, string deviceID) {
            object[] results = this.Invoke("Login", new object[] {
                        loginNaam,
                        wachtwoord,
                        deviceID});
            return ((LoginResultaat)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginLogin(string loginNaam, string wachtwoord, string deviceID, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Login", new object[] {
                        loginNaam,
                        wachtwoord,
                        deviceID}, callback, asyncState);
        }
        
        /// <remarks/>
        public LoginResultaat EndLogin(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((LoginResultaat)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GeefCaseLoad", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CaseloadResult GeefCaseLoad(string loginToken) {
            object[] results = this.Invoke("GeefCaseLoad", new object[] {
                        loginToken});
            return ((CaseloadResult)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGeefCaseLoad(string loginToken, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GeefCaseLoad", new object[] {
                        loginToken}, callback, asyncState);
        }
        
        /// <remarks/>
        public CaseloadResult EndGeefCaseLoad(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((CaseloadResult)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/VoegContactJournaalToe", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SessionStatus VoegContactJournaalToe(string loginToken, string onderwerp, string inhoud, int hulpverleningID, System.DateTime datum) {
            object[] results = this.Invoke("VoegContactJournaalToe", new object[] {
                        loginToken,
                        onderwerp,
                        inhoud,
                        hulpverleningID,
                        datum});
            return ((SessionStatus)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginVoegContactJournaalToe(string loginToken, string onderwerp, string inhoud, int hulpverleningID, System.DateTime datum, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("VoegContactJournaalToe", new object[] {
                        loginToken,
                        onderwerp,
                        inhoud,
                        hulpverleningID,
                        datum}, callback, asyncState);
        }
        
        /// <remarks/>
        public SessionStatus EndVoegContactJournaalToe(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((SessionStatus)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/VoegContactJournalenToe", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SessionStatus VoegContactJournalenToe(string loginToken, ContactJournaal[] journalen) {
            object[] results = this.Invoke("VoegContactJournalenToe", new object[] {
                        loginToken,
                        journalen});
            return ((SessionStatus)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginVoegContactJournalenToe(string loginToken, ContactJournaal[] journalen, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("VoegContactJournalenToe", new object[] {
                        loginToken,
                        journalen}, callback, asyncState);
        }
        
        /// <remarks/>
        public SessionStatus EndVoegContactJournalenToe(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((SessionStatus)(results[0]));
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginResultaat {
        
        /// <remarks/>
        public string NaamMedewerker;
        
        /// <remarks/>
        public LoginStatus Status;
        
        /// <remarks/>
        public string Token;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum LoginStatus {
        
        /// <remarks/>
        Succes,
        
        /// <remarks/>
        ToestelGeblokkeerd,
        
        /// <remarks/>
        OngeldigeGegevens,
        
        /// <remarks/>
        GebruikerGeblokkeerd,
        
        /// <remarks/>
        GeneriekeFout,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ContactJournaal {
        
        /// <remarks/>
        public int HulpVerleningId;
        
        /// <remarks/>
        public string Onderwerp;
        
        /// <remarks/>
        public string Inhoud;
        
        /// <remarks/>
        public System.DateTime Datum;
        
        /// <remarks/>
        public int MedewerkerID;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.qnh.nl/xsd/caseload")]
    public partial class BereikbaarheidType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Bereikbaar")]
        public BereikbaarheidTypeBereikbaar[] Bereikbaar;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.qnh.nl/xsd/caseload")]
    public partial class BereikbaarheidTypeBereikbaar {
        
        /// <remarks/>
        public string Soort;
        
        /// <remarks/>
        public string Waarde;
        
        /// <remarks/>
        public string Opmerkingen;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.qnh.nl/xsd/caseload")]
    public partial class AdresType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Adres")]
        public AdresTypeAdres[] Adres;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.qnh.nl/xsd/caseload")]
    public partial class AdresTypeAdres {
        
        /// <remarks/>
        public string Straat;
        
        /// <remarks/>
        public short HuisNummer;
        
        /// <remarks/>
        public string Postcode;
        
        /// <remarks/>
        public string Plaats;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CaseloadResult {
        
        /// <remarks/>
        public SessionStatus Status;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Jeugdige", Namespace="http://www.qnh.nl/xsd/caseload", IsNullable=false)]
        public JeugdigenJeugdige[] Jeugdigen;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum SessionStatus {
        
        /// <remarks/>
        Ok,
        
        /// <remarks/>
        Verlopen,
        
        /// <remarks/>
        Ongeldig,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.qnh.nl/xsd/caseload")]
    public partial class JeugdigenJeugdige {
        
        /// <remarks/>
        public int Id;
        
        /// <remarks/>
        public int HulpverleningId;
        
        /// <remarks/>
        public string TypeHulpverlening;
        
        /// <remarks/>
        public string IsEersteContactPersoon;
        
        /// <remarks/>
        public string Naam;
        
        /// <remarks/>
        public GeslachtType Geslacht;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime GeboorteDatum;
        
        /// <remarks/>
        public AdresType Adressen;
        
        /// <remarks/>
        public BereikbaarheidType Bereikbaarheid;
        
        /// <remarks/>
        public string Aantekeningen;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Relatie", IsNullable=false)]
        public ArrayOfJeugdigenJeugdigeRelatieRelatie[] Relaties;
        
        /// <remarks/>
        public JeugdigenJeugdigeContactJournaals ContactJournaals;
        
        /// <remarks/>
        public JeugdigenJeugdigeSamenvatting Samenvatting;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.qnh.nl/xsd/caseload")]
    public enum GeslachtType {
        
        /// <remarks/>
        M,
        
        /// <remarks/>
        V,
        
        /// <remarks/>
        O,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.qnh.nl/xsd/caseload")]
    public partial class ArrayOfJeugdigenJeugdigeRelatieRelatie {
        
        /// <remarks/>
        public string Soort;
        
        /// <remarks/>
        public int Id;
        
        /// <remarks/>
        public string Naam;
        
        /// <remarks/>
        public GeslachtType Geslacht;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime GeboorteDatum;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool GeboorteDatumSpecified;
        
        /// <remarks/>
        public AdresType Adressen;
        
        /// <remarks/>
        public BereikbaarheidType Bereikbaarheid;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.qnh.nl/xsd/caseload")]
    public partial class JeugdigenJeugdigeContactJournaals {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ContactJournaal")]
        public JeugdigenJeugdigeContactJournaalsContactJournaal[] ContactJournaal;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.qnh.nl/xsd/caseload")]
    public partial class JeugdigenJeugdigeContactJournaalsContactJournaal {
        
        /// <remarks/>
        public int Id;
        
        /// <remarks/>
        public string Inhoud;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime Datum;
        
        /// <remarks/>
        public string Medewerker;
        
        /// <remarks/>
        public string Omschrijving;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.qnh.nl/xsd/caseload")]
    public partial class JeugdigenJeugdigeSamenvatting {
        
        /// <remarks/>
        public string Gezag;
        
        /// <remarks/>
        public string Zorg;
        
        /// <remarks/>
        public string Beschikking;
    }
}
